In [2]:
import numpy as np 
import torch 

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = torch.from_numpy(a)

In [6]:
b

tensor([1, 2, 3, 4])

In [8]:
b[0] = 5

In [9]:
b

tensor([5, 2, 3, 4])

In [10]:
a

array([5, 2, 3, 4])

In [11]:
c = np.array([1,2,3,4])
d = torch.from_numpy(c.copy())

In [12]:
print(c, d)

[1 2 3 4] tensor([1, 2, 3, 4])


In [13]:
d[0]= 66
print(c, d)

[1 2 3 4] tensor([66,  2,  3,  4])


In [36]:
a = torch.randn((3, 6, 5)) 
print(a.shape)

torch.Size([3, 6, 5])


In [37]:
b = a.reshape(-1, 3)
print(b.shape)
c = a.view(-1, 3)
print(c.shape)
print(a.shape)

torch.Size([30, 3])
torch.Size([30, 3])
torch.Size([3, 6, 5])


In [38]:
a

tensor([[[ 0.6230, -0.2535, -0.6327,  0.2179,  0.1705],
         [-0.1252, -0.8863, -0.2784,  1.4400, -0.1844],
         [-0.5756, -0.3435, -0.4829, -0.1762, -0.4022],
         [-0.2411, -0.3408, -0.5830, -0.8472,  0.2182],
         [ 0.2920,  0.8156, -0.2062,  0.5853, -0.1402],
         [ 0.0669,  1.2398, -1.2058, -0.6404,  0.5988]],

        [[ 0.5643, -1.9855, -2.0185,  0.1343,  1.2408],
         [ 0.7136,  1.5999,  0.6695, -0.6390,  0.4396],
         [-1.6188,  1.4857,  1.3700, -2.8871,  0.3280],
         [ 0.7138, -0.8965, -0.5238,  1.1967, -0.0602],
         [-0.3375, -0.1900, -1.7171, -0.2760, -1.8637],
         [ 0.9588,  0.9568, -0.1394, -0.4637,  0.0655]],

        [[ 1.0389,  0.3920,  0.5829,  1.2512,  0.0149],
         [ 0.0528,  0.9716,  0.2211, -0.8725,  0.5200],
         [-0.7701, -0.7006,  1.1537,  0.0054, -0.5289],
         [ 0.4683, -0.5446, -0.3292, -0.9832, -0.0469],
         [-0.6551, -0.2791,  0.3822, -0.8476,  1.3836],
         [-1.0871,  0.8806,  1.1768, -0.4254

In [39]:
a[0][0][0] 

tensor(0.6230)

In [40]:
c[0][0]

tensor(0.6230)

In [41]:
c[0][0] = 10
print(c[0][0])

tensor(10.)


In [42]:
c

tensor([[ 1.0000e+01, -2.5350e-01, -6.3271e-01],
        [ 2.1786e-01,  1.7053e-01, -1.2515e-01],
        [-8.8629e-01, -2.7844e-01,  1.4400e+00],
        [-1.8437e-01, -5.7556e-01, -3.4351e-01],
        [-4.8291e-01, -1.7623e-01, -4.0224e-01],
        [-2.4110e-01, -3.4077e-01, -5.8304e-01],
        [-8.4716e-01,  2.1824e-01,  2.9201e-01],
        [ 8.1558e-01, -2.0618e-01,  5.8529e-01],
        [-1.4023e-01,  6.6875e-02,  1.2398e+00],
        [-1.2058e+00, -6.4041e-01,  5.9881e-01],
        [ 5.6433e-01, -1.9855e+00, -2.0185e+00],
        [ 1.3427e-01,  1.2408e+00,  7.1358e-01],
        [ 1.5999e+00,  6.6949e-01, -6.3898e-01],
        [ 4.3960e-01, -1.6188e+00,  1.4857e+00],
        [ 1.3700e+00, -2.8871e+00,  3.2801e-01],
        [ 7.1380e-01, -8.9650e-01, -5.2381e-01],
        [ 1.1967e+00, -6.0176e-02, -3.3749e-01],
        [-1.8995e-01, -1.7171e+00, -2.7598e-01],
        [-1.8637e+00,  9.5876e-01,  9.5681e-01],
        [-1.3939e-01, -4.6369e-01,  6.5484e-02],
        [ 1.0389e+00

In [43]:
a

tensor([[[ 1.0000e+01, -2.5350e-01, -6.3271e-01,  2.1786e-01,  1.7053e-01],
         [-1.2515e-01, -8.8629e-01, -2.7844e-01,  1.4400e+00, -1.8437e-01],
         [-5.7556e-01, -3.4351e-01, -4.8291e-01, -1.7623e-01, -4.0224e-01],
         [-2.4110e-01, -3.4077e-01, -5.8304e-01, -8.4716e-01,  2.1824e-01],
         [ 2.9201e-01,  8.1558e-01, -2.0618e-01,  5.8529e-01, -1.4023e-01],
         [ 6.6875e-02,  1.2398e+00, -1.2058e+00, -6.4041e-01,  5.9881e-01]],

        [[ 5.6433e-01, -1.9855e+00, -2.0185e+00,  1.3427e-01,  1.2408e+00],
         [ 7.1358e-01,  1.5999e+00,  6.6949e-01, -6.3898e-01,  4.3960e-01],
         [-1.6188e+00,  1.4857e+00,  1.3700e+00, -2.8871e+00,  3.2801e-01],
         [ 7.1380e-01, -8.9650e-01, -5.2381e-01,  1.1967e+00, -6.0176e-02],
         [-3.3749e-01, -1.8995e-01, -1.7171e+00, -2.7598e-01, -1.8637e+00],
         [ 9.5876e-01,  9.5681e-01, -1.3939e-01, -4.6369e-01,  6.5484e-02]],

        [[ 1.0389e+00,  3.9203e-01,  5.8287e-01,  1.2512e+00,  1.4901e-02],
        

In [44]:
b

tensor([[ 1.0000e+01, -2.5350e-01, -6.3271e-01],
        [ 2.1786e-01,  1.7053e-01, -1.2515e-01],
        [-8.8629e-01, -2.7844e-01,  1.4400e+00],
        [-1.8437e-01, -5.7556e-01, -3.4351e-01],
        [-4.8291e-01, -1.7623e-01, -4.0224e-01],
        [-2.4110e-01, -3.4077e-01, -5.8304e-01],
        [-8.4716e-01,  2.1824e-01,  2.9201e-01],
        [ 8.1558e-01, -2.0618e-01,  5.8529e-01],
        [-1.4023e-01,  6.6875e-02,  1.2398e+00],
        [-1.2058e+00, -6.4041e-01,  5.9881e-01],
        [ 5.6433e-01, -1.9855e+00, -2.0185e+00],
        [ 1.3427e-01,  1.2408e+00,  7.1358e-01],
        [ 1.5999e+00,  6.6949e-01, -6.3898e-01],
        [ 4.3960e-01, -1.6188e+00,  1.4857e+00],
        [ 1.3700e+00, -2.8871e+00,  3.2801e-01],
        [ 7.1380e-01, -8.9650e-01, -5.2381e-01],
        [ 1.1967e+00, -6.0176e-02, -3.3749e-01],
        [-1.8995e-01, -1.7171e+00, -2.7598e-01],
        [-1.8637e+00,  9.5876e-01,  9.5681e-01],
        [-1.3939e-01, -4.6369e-01,  6.5484e-02],
        [ 1.0389e+00

In [45]:
a = torch.randn(1, 2, 3, 4)

In [46]:
b = a.transpose(1, 2)
print(b.shape)

torch.Size([1, 3, 2, 4])


In [47]:
a.is_contiguous()

True

In [48]:
b.is_contiguous()

False

In [51]:
c = b.reshape(1, 2, 3, 4)

In [53]:
b[0][0][0][0] = 10 

In [54]:
b

tensor([[[[10.0000, -0.2882,  0.6770, -0.5260],
          [ 0.2297, -1.9821, -0.9234, -1.2773]],

         [[ 0.9998, -1.0288,  1.9755,  0.1396],
          [ 1.9039, -0.9955, -0.0840, -0.1360]],

         [[ 1.2485,  1.1290,  1.7642, -0.9494],
          [ 0.3976,  0.8728, -0.2925, -0.5866]]]])

In [55]:
c

tensor([[[[-1.0081, -0.2882,  0.6770, -0.5260],
          [ 0.2297, -1.9821, -0.9234, -1.2773],
          [ 0.9998, -1.0288,  1.9755,  0.1396]],

         [[ 1.9039, -0.9955, -0.0840, -0.1360],
          [ 1.2485,  1.1290,  1.7642, -0.9494],
          [ 0.3976,  0.8728, -0.2925, -0.5866]]]])